phenomnomnominal/betterer

- README.md
- packages/betterer/package.json
- packages/betterer/src/betterer.ts
- packages/betterer/src/types.ts
- packages/constraints/README.md
- packages/constraints/src/bigger.ts
- packages/constraints/src/constraint-result.ts
- packages/constraints/src/index.ts
- packages/constraints/src/smaller.ts
Turns out there are cases where you want to have more contorl of what it looks like for values to be the same. This adds an enum which allows you to do that, and updates the existing constraints.
> (refactoring :hammer:) - constraints now control what "same" means

- packages/betterer/src/betterer.ts
- packages/betterer/src/serialiser.ts
- packages/betterer/src/stringifier.ts
- packages/betterer/src/types.ts
- packages/eslint/src/eslint.ts
- packages/regexp/src/regexp.ts
- packages/tsquery/src/tsquery.ts
- packages/typescript/src/typescript.ts
The current serialisation logic is a bit hard to follow, and pretty inflexible for types beyond numbers. This improves that. It also makes it do that the .results file won't be updated if the values haven't changed so you have a stable date of when the value was last improved.
> (refactoring :hammer:) - making it easier to reason about serialisation

- README.md
`useStrict` isn't a valid ts config option and it's tripped me up a few times, ha.
> Correct ts strict config documentation

- packages/betterer/src/printer.ts
Fixes #24 
Typescript (and potentially other things) can output a  ` symbol in their results which would break the snapshot formatting.
> Ensure snapshots don't break due to invalid syntax

- packages/betterer/package.json
- packages/betterer/src/files/file-info.ts
- packages/betterer/src/printer.ts
- test/__snapshots__/betterer-eslint.spec.ts.snap
- yarn.lock
This really needs some good tests, but after a few days of poking I _finally_ got our ts checks working again. 
I don't have a minimal reproduction right now, but you can reproduce the failure on https://github.com/artsy/reaction/pull/2864 easily enough. 
To repo:
1. delete the `.betterer.results` file
2. run `yarn betterer` (which will generate the results file)
3. run `yarn betterer` again. 
On the last step betterer will fail with somewhat vague error about not being able to read the results (see below). Ultimately the error is caused by a `JSON.parse` that blows up. 
```
☀️  betterer  erro  🔥  -  could not read results from "~/Git/artsy/reaction/.betterer.results". 😔
(node:38146) UnhandledPromiseRejectionWarning: Error
at Object.<anonymous> …
```
> Ensure serialized ts errors can be read back in

- .gitignore
- fixtures/test-betterer-typescript/tsconfig.json
- package.json
- packages/betterer/package.json
- packages/betterer/tsconfig.json
- packages/cli/package.json
- packages/cli/tsconfig.json
- packages/constraints/package.json
- packages/constraints/tsconfig.json
- packages/eslint/package.json
- packages/eslint/tsconfig.json
- packages/logger/package.json
- packages/logger/tsconfig.json
- packages/regexp/package.json
- packages/regexp/tsconfig.json
- packages/tsconfig.json
- packages/tsquery/package.json
- packages/tsquery/tsconfig.json
- packages/typescript/package.json
- packages/typescript/tsconfig.json
- tsconfig.json
Fixes #18 
This adds support for typescript incremental compilation and project references. Essentially, when the project builds it actually builds each individual project, but only when it's needed. It'll keep a cache version around and each project knows about its dependencies and _won't_ recompile them if they haven't changed. This'll  make development _much_ faster.
> Add ts incremental compilation

- .betterer.results
- packages/betterer/src/context/context.ts
- packages/betterer/src/context/run.ts
- packages/betterer/src/context/statistics.ts
- packages/betterer/src/runner/runner.ts
- packages/logger/src/logger.ts
- packages/reporter/src/messages.ts
- packages/reporter/src/reporter.ts
- packages/watch-reporter/src/reporter.ts
- test/__snapshots__/betterer-eslint-complex.spec.ts.snap
- test/__snapshots__/betterer-eslint.spec.ts.snap
- test/__snapshots__/betterer-regexp.spec.ts.snap
- test/__snapshots__/betterer-tsquery.spec.ts.snap
- test/__snapshots__/betterer-typescript-strict.spec.ts.snap
- test/__snapshots__/betterer-typescript.spec.ts.snap
- test/__snapshots__/betterer-worse.spec.ts.snap
- test/betterer-worse.spec.ts
This means that a `betterer -u` will be reported as an update instead of a failure
And it will have exitCode=1
> feat(betterer ✨): differentiate between `worse` and `updated`

- .betterer.results
- README.md
- packages/betterer/src/context/run.ts
- packages/betterer/src/results/printer.ts
- packages/betterer/src/results/types.ts
- packages/betterer/src/results/writer.ts
- packages/betterer/src/runner/runner.ts
- packages/extension/src/server/validator.ts
- test/__snapshots__/betterer-better.spec.ts.snap
- test/__snapshots__/betterer-complete.spec.ts.snap
- test/__snapshots__/betterer-config-ts-esm.spec.ts.snap
- test/__snapshots__/betterer-config-ts.spec.ts.snap
- test/__snapshots__/betterer-conflict.spec.ts.snap
- test/__snapshots__/betterer-deadline.spec.ts.snap
- test/__snapshots__/betterer-eslint-complex.spec.ts.snap
- test/__snapshots__/betterer-eslint-options.spec.ts.snap
- test/__snapshots__/betterer-eslint.spec.ts.snap
- test/__snapshots__/betterer-exclude.spec.ts.snap
- test/__snapshots__/betterer-failed.spec.ts.snap
- test/__snapshots__/betterer-named-exports.spec.ts.snap
- test/__snapshots__/betterer-only.spec.ts.snap
- test/__snapshots__/betterer-regexp.spec.ts.snap
- test/__snapshots__/betterer-same.spec.ts.snap
- test/__snapshots__/betterer-skip.spec.ts.snap
- test/__snapshots__/betterer-tsquery.spec.ts.snap
- test/__snapshots__/betterer-typescript-strict.spec.ts.snap
- test/__snapshots__/betterer-typescript.spec.ts.snap
- test/__snapshots__/betterer-worse.spec.ts.snap
- test/betterer-conflict.spec.ts
Timestamps are causing weird merge issues in the the results file, and they don't provide much value.
Leaving most of the implementation in place so they can be used from reporters.
Bumping the version number in the header so it can be detected if needed.
BREAKING CHANGE: Remove timestamps from results file
> feat(betterer ✨): removing timestamps

- .betterer.results
- packages/eslint/src/eslint.ts
- packages/extension/src/server/validator.ts
Fixes a bug where eslintrc isn't executed in the project directory, causing rulesets that use the
working directory to determine their rules to fail.
Does this by changing directory to the project before executing checks
> fix(extension 🐛): cd to project dir before making checks

- packages/extension/src/client/commands/names.ts
- packages/extension/src/client/extension.ts
- packages/extension/src/client/status.ts
This closes https://github.com/phenomnomnominal/betterer/issues/207
> fix(extension 🐛): can't launch VSC extension due to wrong command name

- README.md
- packages/betterer/src/runner/runner.ts
- packages/betterer/src/test/file-test/constraint.ts
- packages/betterer/src/test/file-test/file-test.ts
- packages/betterer/src/test/types.ts
- packages/constraints/src/bigger.ts
- packages/constraints/src/constraint-result.ts
- packages/constraints/src/index.ts
- packages/constraints/src/smaller.ts
Renames `ConstraintResult` to `BettererConstraintResult`
> fix(betterer 🐛): rename `ConstraintResult`

- packages/betterer/src/test/file-test/file-resolver.ts
- packages/typescript/src/typescript.ts
> fix(typescript 🐛): fix replacing paths in error messages

- goldens/api/@betterer/betterer.d.ts
- packages/betterer/src/context/context.ts
- packages/betterer/src/context/run.ts
- packages/betterer/src/context/types.ts
- packages/betterer/src/results/deserialiser.ts
- packages/betterer/src/results/printer.ts
- packages/betterer/src/test/index.ts
- packages/betterer/src/test/test.ts
- packages/betterer/src/test/types.ts
- packages/reporter/src/reporter.ts
- packages/watch-reporter/src/reporter.ts
Move `name` from BettererTest to BettererRun
> fix(betterer 🐛): more name from test to run

- .betterer.results
- packages/betterer/src/test/file-test/file.ts
- packages/cli/src/watch.ts
- packages/extension/src/client/commands/disable.ts
- packages/extension/src/client/commands/enable.ts
- packages/extension/src/client/commands/init.ts
- packages/extension/src/client/extension.ts
- packages/extension/src/client/requests/state.ts
- packages/extension/src/client/settings.ts
- packages/extension/src/client/status.ts
- packages/extension/src/server/server.ts
- packages/extension/src/server/validator.ts
I fixed the `no-floating-promises` errors by marking the promises as ignored with the `void` operator.
Issue: https://github.com/phenomnomnominal/betterer/issues/116
> fix(eslint 🐛): fix no-floating-promises errors

- packages/typescript/src/typescript.ts
Hi everyone!
I think Betterer looks like a good idea so I wanted to try it. Sadly I ran with our tsconfig.json into an error while using @betterer/typescript.
```
TypeError: Cannot read property 'fileName' of undefined
at [..]\node_modules\@betterer\typescript\src\typescript.ts:69:9
at Array.reduce (<anonymous>)
at Object.<anonymous> ([..]\node_modules\@betterer\typescript\src\typescript.ts:62:27)
at step ([..]\node_modules\tslib\tslib.js:140:27)
at Object.next ([..]\node_modules\tslib\tslib.js:121:57)
at fulfilled ([..]\node_modules\tslib\tslib.js:111:62)
```
The diagnostics object in the reduce callback looks like this:
```
{ file: undefined,
start: undefined,
length: undefined,
messageText:
'Option \'--incremental\' can only be specified using tsconfig, emitting to single file or when …
```
> [typescript] Prevent error when there is no location for diagnostic

- README.md
Hey!
I was trying betterer out on a JS repo today and encountered an error. 
```
npx betterer
Error: Cannot find module 'typescript'
Require stack:
- [REDACTED]/node_modules/ts-node/dist/index.js
...
```
Looks like typescript is required due to ts-node. Hopefully this README update helps!
> docs: mention that typescript is required

- packages/extension/src/server/validator.ts
This combines the issues found from all runs into one set of diagnostics to pass to VS Code (see https://github.com/phenomnomnominal/betterer/issues/224#issuecomment-827187113).
I couldn't get the e2e tests working or else I would have tried to add a test :(. They opened VS Code, and it say on the home screen for a while... then eventually closed with no tests actually running.
However I can confirm that with this change, and my config (see https://github.com/phenomnomnominal/betterer/pull/650#issuecomment-827197501), I'm getting betterer warnings in VS Code now:
> Report issues from all runs in VS Code extension

- packages/betterer/src/test/file-test/serialiser.ts
> fix(betterer 🐛): make sure results file stays in the same order

- packages/cli/src/options.ts
- packages/cli/src/start.ts
- test/cli/__snapshots__/betterer-ci.spec.ts.snap
- test/cli/betterer-ci.spec.ts
> feat(betterer ✨): enable CI mode when CI env variable is set

- goldens/api/@betterer/betterer.d.ts
- packages/betterer/src/context/context.ts
- packages/betterer/src/context/run-summary.ts
- packages/betterer/src/context/run.ts
- packages/betterer/src/context/types.ts
- packages/betterer/src/index.ts
- packages/betterer/src/results/results.ts
- packages/betterer/src/test/file-test/file-test.ts
- packages/betterer/src/test/index.ts
- packages/betterer/src/test/public.ts
- packages/betterer/src/test/type.ts
- packages/reporter/src/components/runs/deltas/delta.ts
BREAKING CHANGE: run.filePaths can be null for a global test
> refactor(betterer 🔧): run.filePaths only defined on file tests

- goldens/api/@betterer/tsquery.d.ts
- goldens/api/@betterer/typescript.d.ts
- packages/extension/test/test.e2e-spec.ts
- packages/tsquery/src/index.ts
- packages/tsquery/src/tsquery.ts
- packages/typescript/src/index.ts
- packages/typescript/src/typescript.ts
- test/__snapshots__/betterer-tsquery.spec.ts.snap
- test/__snapshots__/betterer-typescript.spec.ts.snap
- test/betterer-better.spec.ts
- test/betterer-conflict.spec.ts
- test/betterer-same.spec.ts
- test/betterer-tsquery.spec.ts
- test/betterer-typescript-strict.spec.ts
- test/betterer-typescript.spec.ts
- test/betterer-worse.spec.ts
- test/cli/betterer-ci.spec.ts
- test/cli/betterer-precommit.spec.ts
- test/runner/__snapshots__/betterer-runner.spec.ts.snap
- test/runner/betterer-runner.spec.ts
- test/watch/betterer-watch.spec.ts
- website/docs/built-in-tests.md
BREAKING CHANGE: tsquery no longer requires tsconfig
> refactor(betterer 🔧):  update typescript and tsquery

- packages/betterer/package.json
- packages/betterer/src/fs/version-control.ts
- yarn.lock
Pass parent `.git` directory to `simple-git` when the git directory is resolved to `.git/worktrees/etc` or `.git/modules/etc`.
Honestly since worktrees are local only things... I think a unit test would be difficult. It'd probably have to set up a worktree, put code into it, and test betterer there? I just made a test repo and verified the change works. If you have other ideas for tests, let me know.
Fixes #786
> Fix error when using worktrees or submodules

- packages/betterer/src/test/file-test/file-test-result.ts
- packages/betterer/src/test/file-test/serialiser.ts
- test/__snapshots__/betterer-file-test.spec.ts.snap
- test/betterer-file-test.spec.ts
Since sorting is now handled upstream in `file-test`, the `sort` in the printer causes absolute paths mixed in with relative paths to sort incorrectly. We know the results are sorted correctly already, so we can just remove the sort and call it good.
This could potentially mean that non-file-test results get reordered arbitrarily... but all tests pass, so looks like there weren't checks for that.
Also added `fixtures` to jest ignores to prevent infinite watch loop when running jest in watch mode.
> Fix results reordering if ran on a single file

- goldens/api/betterer.api.md
- packages/betterer/src/config/config.ts
- packages/betterer/src/config/index.ts
- packages/betterer/src/config/types.ts
- packages/betterer/src/context/context.ts
- packages/betterer/src/fs/git.ts
- packages/betterer/src/globals.ts
- packages/betterer/src/run/worker-run-config.ts
- packages/betterer/src/run/worker-run.ts
- test/config-validation.spec.ts
> fix(betterer 🐛): use repository root when rewriting paths in results file

- packages/betterer/src/test/file-test/file.ts
- test/__snapshots__/file-test-line-endings.spec.ts.snap
- test/file-test-line-endings.spec.ts
Fixes #985 
I think this could cause issues with displaying errors in the extension, but I'm okay with that for now.
> fix(betterer 🐛): normalise issue text before creating issue

- packages/betterer/src/config/config.ts
- packages/betterer/src/fs/git.ts
I've been trying to use Betterer in a github action (for context, see https://github.com/grafana/grafana-github-actions/blob/main/backport/backport.ts#L95)
In doing so I noticed that it's impossible to run Betterer from outside of the repo itself even if you specify a `cwd` inside the repo. I think that's because the `cwd` is never passed to `findGitRoot` and it only ever uses `process.cwd()`. In comparison, it finds the config files correctly because `cwd` is passed through to `validateConfigPaths`.
> Correctly use the `cwd` option when looking for the `.git` root

- website/docs/typescript-test.md
Prevent accidentally generating typescript files when following the docs.
> docs(typescript): add noEmit true option to typescript text example
