README.md

(docs 📖) - fix typo in readme

---

packages/betterer/src/betterer.ts
packages/betterer/src/config.ts
packages/betterer/src/types.ts

It's useful to have access to the current config, this is a pretty naive way to do it (yay singleton!), but it will do for now!

(refactoring :hammer:) - add the ability to read the config

---

packages/betterer/src/files/file-info.ts
packages/betterer/src/printer.ts
packages/betterer/test/printer.spec.ts

This builds off of the work you've already done in betterer-diffs to add two things:
1. New lines in the results file when given a json payload
2. The ability to additionally specify error messages
As an example, here's the diff of the results (with my changes) when you fix one error in a file
```diff
diff --git a/.betterer.results b/.betterer.results
index 716de29d2..f238c7463 100644
--- a/.betterer.results
+++ b/.betterer.results
@@ -1,5 +1,5 @@
// BETTERER RESULTS V1.
-exports[`stricter compilation`] = { timestamp: 1571267154321, value: `{
+exports[`stricter compilation`] = { timestamp: 1571267292707, value: `{
"../src/Apps/__stories__/Apps.story.tsx":[[101,21]],
"../src/Apps/__stories__/ArtistApp.story.tsx":[[101,21]],
"../src/Apps/__stories__/ArtworkApp.story.tsx":[[101,21]],
@@ …
```

Enhance serialization for ease of use/tooling

---

.betterer.ts
README.md
fixtures/test-betterer-config-ts/.betterer.ts
fixtures/test-betterer-config-ts/package.json
packages/betterer/README.md
packages/betterer/package.json
packages/betterer/src/index.ts
packages/cli/src/constants.ts
test/__snapshots__/betterer-config-ts.spec.ts.snap
test/betterer-better.spec.ts
test/betterer-complete.spec.ts
test/betterer-config-ts.spec.ts
test/betterer-eslint.spec.ts
test/betterer-filter.spec.ts
test/betterer-init.spec.ts
test/betterer-regexp.spec.ts
test/betterer-same.spec.ts
test/betterer-worse.spec.ts
yarn.lock

(feat :sparkles:) - enable .betterer.ts config file

---

fixtures/test-betterer-typescript/.betterer.ts
fixtures/test-betterer-typescript/package.json
fixtures/test-betterer-typescript/tsconfig.json
packages/betterer/src/index.ts
test/__snapshots__/betterer-typescript.spec.ts.snap
test/betterer-typescript.spec.ts

(test :rotating_light:) - adding test for @betterer/typescript

---

packages/betterer/src/printer.ts
packages/typescript/src/typescript.ts

Fixes #28 
Replaces absolute paths with its relative equivalent when outputting absolute  paths.

Replace absolute paths with relative paths to cwd

---

fixtures/test-betterer-config-ts-esm/.betterer.ts
fixtures/test-betterer-config-ts-esm/package.json
fixtures/test-betterer-config-ts-esm/tsconfig.json
packages/betterer/src/register.ts
test/__snapshots__/betterer-config-ts-esm.spec.ts.snap
test/betterer-config-ts-esm.spec.ts

Should fix #65
I can see this biting me in the face later 😅

(fix :bug:) - fix for handling TS files with ES import syntax

---

packages/betterer/src/context/run.ts
packages/betterer/src/test/file-test/constraint.ts
packages/betterer/src/test/file-test/file-test.ts

* if none of the files change but the test implementation changes
* if the test is skipped on its first run

(fix :bug:) - fix a couple cases I didn't consider

---

.betterer.results
packages/betterer/src/results/printer.ts
test/__snapshots__/betterer-better.spec.ts.snap
test/__snapshots__/betterer-config-ts-esm.spec.ts.snap
test/__snapshots__/betterer-config-ts.spec.ts.snap
test/__snapshots__/betterer-deadline.spec.ts.snap
test/__snapshots__/betterer-eslint-complex.spec.ts.snap
test/__snapshots__/betterer-eslint-options.spec.ts.snap
test/__snapshots__/betterer-eslint.spec.ts.snap
test/__snapshots__/betterer-exclude.spec.ts.snap
test/__snapshots__/betterer-failed.spec.ts.snap
test/__snapshots__/betterer-named-exports.spec.ts.snap
test/__snapshots__/betterer-only.spec.ts.snap
test/__snapshots__/betterer-regexp.spec.ts.snap
test/__snapshots__/betterer-same.spec.ts.snap
test/__snapshots__/betterer-skip.spec.ts.snap
test/__snapshots__/betterer-tsquery.spec.ts.snap
test/__snapshots__/betterer-typescript-strict.spec.ts.snap
test/__snapshots__/betterer-typescript.spec.ts.snap
test/__snapshots__/betterer-worse.spec.ts.snap

fix(betterer 🐛): add new line character to the end of the generated reports file

---

.betterer.results
.eslintrc.js
packages/betterer/src/context/context.ts
packages/betterer/src/context/types.ts
packages/betterer/src/test/test.ts
packages/betterer/src/utils.ts

style(prettier 😎): fix @typescript-eslint/ban-types issues

---

.betterer.results
.eslintrc.js
package.json
packages/betterer/src/config/config.ts
packages/betterer/src/require.ts
packages/extension/src/server/config.ts

style(prettier 😎): fix @typescript-eslint/no-unsafe-return issues

---

.betterer.ts
.eslintrc.js

style(betterer 😎): enable no-unsafe-call and no-unsafe-member-access

---

.betterer.results
goldens/api/@betterer/betterer.d.ts
packages/betterer/src/betterer.ts
packages/extension/src/server/server.ts
packages/extension/src/server/validator.ts
test/betterer-failed.spec.ts
test/file/betterer-file.spec.ts

Rename betterer.single to betterer.file

fix(betterer 🐛): rename betterer.single to betterer.file

---

goldens/api/@betterer/betterer.d.ts
packages/betterer/src/config/config.ts
packages/betterer/src/config/index.ts
packages/betterer/src/context/context.ts
packages/betterer/src/context/run.ts
packages/betterer/src/context/types.ts
packages/betterer/src/results/deserialiser.ts
packages/betterer/src/results/serialiser.ts
packages/betterer/src/runner/runner.ts
packages/betterer/src/test/file-test/file-test.ts
packages/betterer/src/test/file-test/serialiser.ts
packages/betterer/src/test/types.ts
packages/betterer/src/utils.ts

* remove context from BettererRun
* BettererSerialise/Deserialise no longer accept a BettererRun

fix(betterer 🐛): remove context from BettererRun API

---

.betterer.results
README.md
goldens/api/@betterer/betterer.d.ts
packages/betterer/src/context/context.ts
packages/betterer/src/context/run.ts
packages/betterer/src/context/types.ts
packages/betterer/src/index.ts
packages/betterer/src/results/results.ts
packages/betterer/src/runner/runner.ts
packages/betterer/src/test/config.ts
packages/betterer/src/test/file-test/constraint.ts
packages/betterer/src/test/file-test/differ.ts
packages/betterer/src/test/file-test/file-test-result.ts
packages/betterer/src/test/file-test/file-test.ts
packages/betterer/src/test/file-test/goal.ts
packages/betterer/src/test/file-test/index.ts
packages/betterer/src/test/file-test/public.ts
packages/betterer/src/test/file-test/serialiser.ts
packages/betterer/src/test/file-test/types.ts
packages/betterer/src/test/index.ts
packages/betterer/src/test/public.ts
packages/betterer/src/test/test-state.ts
packages/betterer/src/test/test.ts
packages/betterer/src/test/types.ts
packages/eslint/src/eslint.ts
packages/extension/src/server/validator.ts
packages/regexp/src/regexp.ts
packages/tsquery/src/tsquery.ts
packages/typescript/src/typescript.ts

More simplifying of the BettererTest API

fix(betterer 🐛): simplify BettererFileTest and BettererTest

---

.betterer.results
.betterer.ts
.eslintrc.js
packages/betterer/src/errors.ts
packages/cli/src/errors.ts

fix(eslint 🐛): fix restrict-template-expressions (#115)

---

packages/eslint/package.json
yarn.lock

fix(eslint 🐛): fix eslint peer dependency

---

packages/betterer/src/results/escaper.ts
packages/betterer/src/results/printer.ts
packages/betterer/src/results/reader.ts
packages/betterer/src/utils.ts
test/__snapshots__/betterer-results.spec.ts.snap
test/betterer-results.spec.ts

fix(betterer 🐛): improve results file escaping

---

packages/cli/bin/betterer-ci
test/cli/__snapshots__/betterer-ci.spec.ts.snap
test/cli/betterer-ci.spec.ts

Fixes https://github.com/phenomnomnominal/betterer/issues/595.

fix(betterer 🐛): force ci to fail when results got worse

---

goldens/api/@betterer/betterer.d.ts
packages/betterer/src/context/run.ts
packages/betterer/src/test/config.ts
packages/betterer/src/test/file-test/file-test-result.ts
packages/betterer/src/test/file-test/file-test.ts
packages/betterer/src/test/file-test/types.ts
packages/betterer/src/test/test.ts
packages/betterer/src/test/types.ts
test/__snapshots__/betterer-file-test.spec.ts.snap
test/betterer-file-test.spec.ts
website/docs/api/test.md

feat(betterer ✨): change goal and constraint of BettererFileTest

---

packages/betterer/package.json
packages/betterer/src/reader.ts
packages/betterer/src/runner/file-manager.ts
packages/betterer/src/runner/file-resolver.ts
packages/betterer/src/test/file-test/file-test.ts
test/__snapshots__/betterer-cache.spec.ts.snap
yarn.lock

Sometimes I think I write okay code?! Should improve the situation in #691 
**Before:**
**After**

perf(betterer 🏎): caching and perf improvements

---

goldens/api/@betterer/betterer.d.ts
packages/betterer/package.json
packages/betterer/src/context/context.ts
packages/betterer/src/fs/file-resolver.ts
packages/betterer/src/fs/index.ts
packages/betterer/src/fs/public.ts
packages/betterer/src/fs/types.ts
packages/betterer/src/runner/public.ts
packages/betterer/src/test/config.ts
packages/betterer/src/test/file-test/file-test-result.ts
packages/betterer/src/test/file-test/file-test.ts
packages/betterer/src/test/file-test/types.ts
packages/betterer/src/test/types.ts
packages/eslint/src/eslint.ts
packages/regexp/src/regexp.ts
packages/stylelint/src/stylelint.ts
packages/tsquery/src/tsquery.ts
packages/typescript/src/typescript.ts
test/betterer-results.spec.ts
website/blog/2021-03-01-betterer-and-stylelint.md
website/docs/api/file-test.md
website/docs/tests.md
yarn.lock

BREAKING CHANGE: No more BettererFileResolver magic, simplified public API

refactor(betterer 🔧): simplify BettererFileResolver

---

packages/typescript/src/typescript.ts

Does two things to `typescriptΔ`:
- Filters out diagnostics that aren't part of the `filePaths`
- Filters out 6307 errors that happen because the tsconfig is only now a subset of all possible files that might be imported. 
This means betterer can't catch _legit_ 6307 errors... but it's a lot better(er) behavior than how it was, at least.
Was able to clean the code up a bit too because of the type guard in `filter`.
Didn't add a test though (yet), sorry!

Typescript incremental: filter diagnostics to included file only, fiter import errors

---

packages/cli/bin/betterer-ci
packages/cli/bin/betterer-merge
packages/cli/bin/betterer-precommit
packages/cli/bin/betterer-results
packages/cli/bin/betterer-start

fix(betterer 🐛): exitcode should be 1 when tests fail

---

packages/cli/src/precommit.ts
test/cli/precommit-add.spec.ts
test/cli/precommit-worse.spec.ts

fix(betterer 🐛): precommit should allow tests to get better

---

packages/betterer/src/config/config.ts
test/reporter-local-ts.spec.ts

fix(betterer 🐛): you should be able to write a reporter in TS

---

packages/betterer/src/run/worker-run.ts
test/better-result.spec.ts
test/worse-result.spec.ts

fix(betterer 🐛): add missing diff to summary when run is better

---

.github/workflows/build.yaml
packages/betterer/src/run/run.ts
packages/betterer/src/utils.ts
packages/extension/src/server/validation-queue.ts
packages/fixture/src/stubs.ts
packages/tasks/src/tasks/useTasksState.ts
packages/tasks/src/tasks/useTimer.ts
packages/tasks/src/utils.ts
test/deadline-file-test-expired.spec.ts
test/deadline-future.spec.ts
test/setup.ts

test(betterer 🚨): improve date and time mocking
